// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixsenzzibrnlxntbskoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4c2VuenppYnJubHhudGJza29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNjg1ODcsImV4cCI6MjA2OTc0NDU4N30.tWzkDO7vYDr4gKhKUYii0-NzBmE8Ftc_rV28CvLE10c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});